import {z} from "zod";
// Narrowed to just the tables the generic CRUD form actually writes to, so
// PostgREST's typed client can validate .from(table)/.eq("id",...) calls
// without every table in the schema being a candidate.
export type ResourceTable="products"|"product_variants"|"categories"|"brands"|"discount_codes"|"shipping_zones"|"site_content";
export type Field={key:string;label:string;type?:"text"|"textarea"|"number"|"checkbox"|"select";options?:string[];required?:boolean};
export type Resource={title:string;table:ResourceTable;permission:string;columns:string[];fields:Field[];schema:z.ZodType;description:string};
const text=z.string().trim().min(1).max(200), optional=z.string().trim().max(10000), slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(150), uuid=z.string().uuid(), nonnegative=z.coerce.number().int().min(0).max(100000000), bool=z.boolean();
const optionalUuid=z.string().trim().refine(v=>v===""||z.string().uuid().safeParse(v).success,"Invalid selection").transform(v=>v||null);
export const resources:Record<string,Resource>={
products:{title:"Products",table:"products",permission:"products.manage",columns:["id","name","sku","slug","price_minor","cost_minor","status"],description:"Prices and cost are in pesewas (GHS × 100). Cost is never shown to customers. Publish only real products ready for sale. Archive products instead of deleting sales history.",fields:[{key:"name",label:"Product name",required:true},{key:"slug",label:"URL slug",required:true},{key:"sku",label:"SKU",required:true},{key:"price_minor",label:"Price in pesewas",type:"number",required:true},{key:"compare_at_minor",label:"Compare-at price in pesewas",type:"number"},{key:"cost_minor",label:"Cost in pesewas (staff only)",type:"number"},{key:"brand_id",label:"Brand"},{key:"description",label:"Description",type:"textarea"},{key:"warranty",label:"Warranty"},{key:"seo_title",label:"SEO title"},{key:"seo_description",label:"SEO description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["draft","active","archived"]},{key:"is_featured",label:"Featured on homepage",type:"checkbox"},{key:"is_best_seller",label:"Best seller",type:"checkbox"},{key:"track_inventory",label:"Track inventory",type:"checkbox"}],schema:z.object({name:text,slug,sku:text,price_minor:nonnegative,compare_at_minor:nonnegative,cost_minor:nonnegative,brand_id:optionalUuid,description:optional,warranty:optional,seo_title:optional,seo_description:optional,status:z.enum(["draft","active","archived"]),is_featured:bool,is_best_seller:bool,track_inventory:bool})},
variants:{title:"Product variants",table:"product_variants",permission:"products.manage",columns:["id","product_id","name","sku","price_minor","status"],description:"Select a product and give each variant a unique SKU. Prices are in pesewas.",fields:[{key:"product_id",label:"Product",required:true},{key:"name",label:"Variant name",required:true},{key:"sku",label:"Variant SKU",required:true},{key:"price_minor",label:"Price in pesewas",type:"number",required:true},{key:"status",label:"Status",type:"select",options:["active","draft","archived"]}],schema:z.object({product_id:uuid,name:text,sku:text,price_minor:nonnegative,status:z.enum(["active","draft","archived"])})},
categories:{title:"Categories",table:"categories",permission:"products.manage",columns:["id","name","slug","description","sort_order","is_active"],description:"Organize the storefront catalog. Deactivate unused categories.",fields:[{key:"name",label:"Name",required:true},{key:"slug",label:"URL slug",required:true},{key:"description",label:"Description",type:"textarea"},{key:"sort_order",label:"Display order",type:"number",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({name:text,slug,description:optional,sort_order:nonnegative,is_active:bool})},
brands:{title:"Brands",table:"brands",permission:"products.manage",columns:["id","name","slug","is_active"],description:"Manage the brands stocked by the store.",fields:[{key:"name",label:"Name",required:true},{key:"slug",label:"URL slug",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({name:text,slug,is_active:bool})},
discounts:{title:"Discounts",table:"discount_codes",permission:"discounts.manage",columns:["id","code","kind","value","minimum_minor","is_active"],description:"Manage codes for the checkout integration. Percentage values must be 1–100; fixed values and minimum spends use pesewas. Payment checkout is not enabled yet.",fields:[{key:"code",label:"Code",required:true},{key:"kind",label:"Type",type:"select",options:["percentage","fixed"]},{key:"value",label:"Value",type:"number",required:true},{key:"minimum_minor",label:"Minimum spend in pesewas",type:"number",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{3,40}$/),kind:z.enum(["percentage","fixed"]),value:z.coerce.number().int().min(1).max(100000000),minimum_minor:nonnegative,is_active:bool}).refine(v=>v.kind!=="percentage"||v.value<=100)},
settings:{title:"Delivery settings",table:"shipping_zones",permission:"settings.manage",columns:["id","name","regions","fee_minor","estimate","is_active"],description:"Configure delivery zones. Region names are separated by commas; delivery fees use pesewas.",fields:[{key:"name",label:"Zone name",required:true},{key:"regions",label:"Regions (comma separated)",required:true},{key:"fee_minor",label:"Delivery fee in pesewas",type:"number",required:true},{key:"estimate",label:"Delivery estimate",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({name:text,regions:z.string().min(1).max(1000).transform(v=>v.split(",").map(s=>s.trim()).filter(Boolean)),fee_minor:nonnegative,estimate:text,is_active:bool})},
content:{title:"Content",table:"site_content",permission:"content.manage",columns:["id","slug","title","is_published"],description:"Publish plain-text information pages at /policies/your-slug. HTML and scripts are never executed.",fields:[{key:"slug",label:"URL slug",required:true},{key:"title",label:"Title",required:true},{key:"body",label:"Page body",type:"textarea",required:true},{key:"is_published",label:"Published",type:"checkbox"}],schema:z.object({slug,title:text,body:z.string().trim().min(1).max(30000),is_published:bool})}
};
export const adminLinks=[["Overview","/admin","admin.access"],...Object.entries(resources).map(([k,v])=>[v.title,"/admin/"+k,v.permission]),["Inventory","/admin/inventory","inventory.manage"],["Orders","/admin/orders","orders.manage"],["Customers","/admin/customers","customers.read"],["Payments","/admin/payments","payments.read"],["Reviews","/admin/reviews","reviews.manage"],["Reports","/admin/reports","reports.read"],["Staff","/admin/staff","staff.manage"],["Audit logs","/admin/audit","audit.read"]];
export const transitions:Record<string,string[]>={pending:["cancelled"],confirmed:["processing","cancelled"],processing:["ready_for_dispatch","cancelled"],ready_for_dispatch:["shipped","cancelled"],shipped:["out_for_delivery"],out_for_delivery:["delivered"],delivered:["returned"],cancelled:[],returned:[]};
