import {z} from "zod";
// Narrowed to just the tables the generic CRUD form actually writes to, so
// PostgREST's typed client can validate .from(table)/.eq("id",...) calls
// without every table in the schema being a candidate.
export type ResourceTable="products"|"product_variants"|"categories"|"brands"|"discount_codes"|"shipping_zones"|"site_content";
export type Field={key:string;label:string;type?:"text"|"textarea"|"number"|"money"|"checkbox"|"select"|"region-multiselect";options?:string[];required?:boolean;hint?:string};
export type Resource={title:string;table:ResourceTable;permission:string;columns:string[];fields:Field[];schema:z.ZodType;description:string};
const text=z.string().trim().min(1).max(200), optional=z.string().trim().max(10000), slug=z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(150), uuid=z.string().uuid(), nonnegative=z.coerce.number().int().min(0).max(100000000), bool=z.boolean();
const optionalUuid=z.string().trim().refine(v=>v===""||z.string().uuid().safeParse(v).success,"Invalid selection").transform(v=>v||null);
// Ghana's 16 administrative regions (2018 split). Used both for the delivery
// zone picker and, indirectly, the checkout region list — which is derived
// from whatever region names are actually attached to shipping zones — so
// keeping this canonical here prevents typo'd or inconsistent region names
// from ever reaching the storefront.
export const GHANA_REGIONS=["Ahafo","Ashanti","Bono","Bono East","Central","Eastern","Greater Accra","North East","Northern","Oti","Savannah","Upper East","Upper West","Volta","Western","Western North"] as const;
export const resources:Record<string,Resource>={
products:{title:"Products",table:"products",permission:"products.manage",columns:["id","name","sku","slug","price_minor","cost_minor","status"],description:"Enter prices and staff-only cost in Ghana cedis (GHS). Cost is never shown to customers. Publish only real products ready for sale. Archive products instead of deleting sales history.",fields:[{key:"name",label:"Product name",required:true},{key:"slug",label:"URL slug",required:true},{key:"sku",label:"SKU",required:true},{key:"price_minor",label:"Price (GHS)",type:"money",required:true},{key:"compare_at_minor",label:"Compare-at price (GHS)",type:"money"},{key:"cost_minor",label:"Cost (GHS, staff only)",type:"money"},{key:"brand_id",label:"Brand"},{key:"description",label:"Description",type:"textarea"},{key:"warranty",label:"Warranty"},{key:"seo_title",label:"SEO title"},{key:"seo_description",label:"SEO description",type:"textarea"},{key:"status",label:"Status",type:"select",options:["draft","active","archived"]},{key:"is_featured",label:"Featured on homepage",type:"checkbox"},{key:"is_best_seller",label:"Best seller",type:"checkbox"},{key:"track_inventory",label:"Track inventory",type:"checkbox"}],schema:z.object({name:text,slug,sku:text,price_minor:nonnegative,compare_at_minor:nonnegative,cost_minor:nonnegative,brand_id:optionalUuid,description:optional,warranty:optional,seo_title:optional,seo_description:optional,status:z.enum(["draft","active","archived"]),is_featured:bool,is_best_seller:bool,track_inventory:bool})},
variants:{title:"Product variants",table:"product_variants",permission:"products.manage",columns:["id","product_id","name","sku","price_minor","status"],description:"Select a product and give each variant a unique SKU. Enter variant prices in Ghana cedis (GHS).",fields:[{key:"product_id",label:"Product",required:true},{key:"name",label:"Variant name",required:true},{key:"sku",label:"Variant SKU",required:true},{key:"price_minor",label:"Price (GHS)",type:"money",required:true},{key:"status",label:"Status",type:"select",options:["active","draft","archived"]}],schema:z.object({product_id:uuid,name:text,sku:text,price_minor:nonnegative,status:z.enum(["active","draft","archived"])})},
categories:{title:"Categories",table:"categories",permission:"products.manage",columns:["id","name","slug","description","sort_order","is_active"],description:"Organize the storefront catalog. Deactivate unused categories.",fields:[{key:"name",label:"Name",required:true},{key:"slug",label:"URL slug",required:true},{key:"description",label:"Description",type:"textarea"},{key:"sort_order",label:"Display order",type:"number",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({name:text,slug,description:optional,sort_order:nonnegative,is_active:bool})},
brands:{title:"Brands",table:"brands",permission:"products.manage",columns:["id","name","slug","is_active"],description:"Manage the brands stocked by the store.",fields:[{key:"name",label:"Name",required:true},{key:"slug",label:"URL slug",required:true},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({name:text,slug,is_active:bool})},
discounts:{title:"Discounts",table:"discount_codes",permission:"discounts.manage",columns:["id","code","kind","value","minimum_minor","is_active"],description:"Manage codes for the checkout integration. Payment checkout is not enabled yet.",fields:[{key:"code",label:"Code",required:true},{key:"kind",label:"Type",type:"select",options:["percentage","fixed"]},{key:"value",label:"Value",type:"number",required:true,hint:"A whole percent (1–100) for Percentage, or a GHS amount (e.g. 20 for GH₵20) for Fixed amount."},{key:"minimum_minor",label:"Minimum spend (GHS)",type:"money"},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9_-]{3,40}$/),kind:z.enum(["percentage","fixed"]),value:z.coerce.number().int().min(1).max(100000000),minimum_minor:nonnegative,is_active:bool}).refine(v=>v.kind!=="percentage"||v.value<=100,{message:"Percentage value must be 100 or less",path:["value"]})},
settings:{title:"Delivery settings",table:"shipping_zones",permission:"settings.manage",columns:["id","name","regions","fee_minor","free_shipping_threshold_minor","estimate","is_active","cod_enabled"],description:"Configure delivery zones. Delivery is free once an order reaches the free-shipping amount; leave that field blank to always charge the delivery fee.",fields:[{key:"cod_enabled",label:"Allow payment on delivery",type:"checkbox"},{key:"name",label:"Zone name",required:true},{key:"regions",label:"Regions served",type:"region-multiselect",required:true},{key:"fee_minor",label:"Delivery fee (GHS)",type:"money",required:true,hint:"Charged on orders below the free-shipping amount."},{key:"free_shipping_threshold_minor",label:"Free shipping from (GHS)",type:"money",hint:"Orders at or above this amount get free delivery. Leave blank to never waive the fee."},{key:"estimate",label:"Estimated delivery time",required:true,hint:"How long delivery takes once dispatched, e.g. \"2-4 business days\"."},{key:"is_active",label:"Active",type:"checkbox"}],schema:z.object({cod_enabled:bool,name:text,regions:z.array(z.enum(GHANA_REGIONS)).min(1,"Select at least one region"),fee_minor:nonnegative,free_shipping_threshold_minor:z.union([nonnegative,z.literal("").transform(()=>null)]).nullable(),estimate:text,is_active:bool})},
content:{title:"Content",table:"site_content",permission:"content.manage",columns:["id","slug","title","is_published"],description:"Publish plain-text information pages at /policies/your-slug. HTML and scripts are never executed.",fields:[{key:"slug",label:"URL slug",required:true},{key:"title",label:"Title",required:true},{key:"body",label:"Page body",type:"textarea",required:true},{key:"is_published",label:"Published",type:"checkbox"}],schema:z.object({slug,title:text,body:z.string().trim().min(1).max(30000),is_published:bool})}
};
export const adminLinks=[["Overview","/admin","admin.access"],...Object.entries(resources).map(([k,v])=>[v.title,"/admin/"+k,v.permission]),["Inventory","/admin/inventory","inventory.manage"],["Orders","/admin/orders","orders.manage"],["Customers","/admin/customers","customers.read"],["Payments","/admin/payments","payments.read"],["Reviews","/admin/reviews","reviews.manage"],["Reports","/admin/reports","reports.read"],["Staff","/admin/staff","staff.manage"],["Audit logs","/admin/audit","audit.read"]];
export const transitions:Record<string,string[]>={pending:["confirmed","cancelled"],confirmed:["processing","cancelled"],processing:["ready_for_dispatch","cancelled"],ready_for_dispatch:["shipped","cancelled"],shipped:["out_for_delivery"],out_for_delivery:["delivered"],delivered:["returned"],cancelled:[],returned:[]};
