import {BusinessContact} from "@/components/business-contact";import { BrandLogo } from "@/components/brand-logo";
import Link from"next/link";import{ArrowRight,BadgeCheck,Headphones,ShieldCheck,Truck}from"lucide-react";import{ProductCard}from"@/components/product-card";import{StoreHeader}from"@/components/store-header";import{getCatalog}from"@/lib/catalog-data";
const footer=[{title:"Shop",links:[["All products","/shop"],["New arrivals","/shop?sort=newest"],["Bulk orders","/bulk-orders"]]},{title:"Help",links:[["Contact","/contact"],["Delivery & FAQ","/faq"],["Returns","/policies/returns"]]},{title:"Company",links:[["About us","/about"],["Privacy","/policies/privacy"],["Terms","/policies/terms"]]}];
export default async function Home(){const{categories,products}=await getCatalog();return <><StoreHeader/><main>
<section className="hero-shell"><div className="hero-copy"><p className="eyebrow">THE PROFESSIONAL EDIT</p><h1>Build a salon<br/>people remember.</h1><p>Premium equipment, considered details, and dependable delivery for Ghana&apos;s beauty professionals.</p><div className="hero-actions"><Link className="button button-dark" href="/shop">Shop equipment <ArrowRight size={17}/></Link><Link className="text-link" href="/bulk-orders">Request a bulk quote</Link></div></div><div className="hero-art"><div className="hero-orb"/><div className="chair"><span/><i/><b/></div><p>New studio collection<br/><strong>Designed for all-day comfort</strong></p></div></section>
<section className="benefits wrap">{[[Truck,"Nationwide delivery","Reliable delivery across Ghana"],[ShieldCheck,"Payment on delivery","In supported delivery zones"],[BadgeCheck,"Professional quality","Equipment selected to perform"],[Headphones,"Real support","Advice before and after purchase"]].map(([Icon,title,text])=><div key={String(title)}><Icon size={22}/><span><strong>{String(title)}</strong><small>{String(text)}</small></span></div>)}</section>
<section className="section wrap"><div className="section-heading"><div><p className="eyebrow">CURATED FOR YOUR SPACE</p><h2>Shop by category</h2></div><Link href="/shop">View all <ArrowRight size={15}/></Link></div><div className="category-grid">{categories.slice(0,4).map((c,i)=><Link href={`/shop?category=${c.slug}`} className={`category category-${i+1}`} key={c.slug}><span>{c.name}</span><small>{c.subtitle}</small><ArrowRight size={18}/></Link>)}</div></section>
<section className="section products-section"><div className="wrap"><div className="section-heading"><div><p className="eyebrow">CUSTOMER FAVOURITES</p><h2>Made for busy professionals</h2></div><Link href="/shop">Shop all products <ArrowRight size={15}/></Link></div><div className="product-grid">{products.filter(p=>p.featured).slice(0,4).map(p=><ProductCard key={p.slug} product={p}/>)}</div></div></section>
<section className="editorial wrap"><div><p className="eyebrow">SALON ESSENTIALS</p><h2>Everything your<br/>station needs.</h2><p>Reliable tools and thoughtful accessories selected for the pace of professional work.</p><Link className="button button-light" href="/shop?category=tools">Explore tools</Link></div><blockquote>“The right equipment doesn&apos;t just fill a space. It helps you deliver your best work, every day.”</blockquote></section>
<section className="newsletter"><div><p className="eyebrow">THE BLEND &amp; BEAM EDIT</p><h2>Better spaces start here.</h2><p>New arrivals, salon inspiration and private offers — sent with restraint.</p></div><form><label className="sr-only" htmlFor="email">Email</label><input id="email" type="email" placeholder="Your email address" required/><button>Join the list <ArrowRight size={16}/></button></form></section></main>
<footer><div className="footer-brand"><BrandLogo inverse /><p>Premium salon equipment and beauty essentials, delivered across Ghana.</p><BusinessContact/></div>{footer.map(group=><div key={group.title}><strong>{group.title}</strong>{group.links.map(([label,href])=><Link href={href} key={label}>{label}</Link>)}</div>)}</footer></>}
